Repository AY2324S1-CS2103-T16-3/tp, pull requests merged in 2023-11, with the labels that each got.

#124 Add line chart to summary statistics window
  src/main/java/unicash/logic/Logic.java
  src/main/java/unicash/logic/LogicManager.java
  src/main/java/unicash/logic/commands/SummaryCommand.java
  src/main/java/unicash/model/Model.java
  src/main/java/unicash/model/ModelManager.java
  src/main/java/unicash/model/UniCash.java
  src/main/java/unicash/model/transaction/DateTime.java
  src/main/java/unicash/model/util/SampleDataUtil.java
  src/main/java/unicash/ui/MainWindow.java
  src/main/java/unicash/ui/SummaryWindow.java
  src/main/resources/images/summary_icon.png
  src/main/resources/view/SummaryWindow.css
  src/main/resources/view/SummaryWindow.fxml
  src/test/data/JsonSerializableUniCashTest/transactionsWithBudgetUniCash.json
  src/test/data/JsonSerializableUniCashTest/typicalTransactionUniCash.json
  src/test/java/unicash/logic/LogicManagerTest.java
  src/test/java/unicash/logic/commands/AddTransactionCommandTest.java
  src/test/java/unicash/logic/commands/SetBudgetCommandTest.java
  src/test/java/unicash/logic/commands/SummaryCommandTest.java
  src/test/java/unicash/model/ModelManagerTest.java
  src/test/java/unicash/model/UniCashTest.java
  src/test/java/unicash/model/transaction/DateTimeTest.java
Labels: priority.High

#137 Add GetTotalExpenditure to UG
  docs/UserGuide.md
  docs/images/unicash/command-outputs/get-total-expenditure/emptyCategory.png
  docs/images/unicash/command-outputs/get-total-expenditure/getTotalExpenditureMonthOnlySuccess.png
  docs/images/unicash/command-outputs/get-total-expenditure/longCategory.png
  docs/images/unicash/command-outputs/get-total-expenditure/monthAndCategory.png
  docs/images/unicash/command-outputs/get-total-expenditure/monthYearCategory.png
  docs/images/unicash/command-outputs/get-total-expenditure/negativeMonth.png
  docs/images/unicash/command-outputs/get-total-expenditure/noMatch.png
  docs/images/unicash/command-outputs/get-total-expenditure/noMonth.png
  docs/images/unicash/command-outputs/get-total-expenditure/nonAlphanumericCategory.png
  docs/images/unicash/command-outputs/get-total-expenditure/nonIntMonth.png
  docs/images/unicash/command-outputs/get-total-expenditure/nonIntYear.png
  docs/images/unicash/command-outputs/get-total-expenditure/oobMonth.png
  docs/images/unicash/command-outputs/get-total-expenditure/oobYear.png
  src/main/java/unicash/logic/commands/GetTotalExpenditureCommand.java
  src/main/java/unicash/logic/parser/GetTotalExpenditureCommandParser.java
  src/test/java/unicash/logic/commands/GetTotalExpenditureCommandTest.java
  src/test/java/unicash/logic/parser/GetTotalExpenditureCommandParserTest.java
Labels: documentation

#141 Changes to the misc section of the DG + updating Ui
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/index.md
Labels: documentation

#143 Addressing potential double overflows in GetTotalExpenditure and GetBudget
  docs/UserGuide.md
  docs/images/unicash/command-outputs/get-budget/getBudgetSuccess.png
  src/main/java/unicash/logic/commands/GetBudgetCommand.java
  src/main/java/unicash/logic/commands/GetTotalExpenditureCommand.java
  src/main/java/unicash/model/commons/Amount.java
  src/test/java/unicash/logic/commands/GetBudgetCommandTest.java
  src/test/java/unicash/model/commons/AmountTest.java
Labels: documentation, type.Bug, severity.High

#142 UI Fix
  src/main/java/unicash/ui/CommandBox.java
  src/main/java/unicash/ui/MainWindow.java
  src/main/java/unicash/ui/StatusBarFooter.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/unicash/ui/CommandBoxUiTest.java
  src/test/java/unicash/ui/MainAppUiTest.java
Labels: severity.Low

#146 Add limit to max number of transactions
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/unicash/AddTransactionActivityDiagram.puml
  docs/images/unicash/AddTransactionActivityDiagram.png
  docs/images/unicash/command-outputs/addTransactionFailedOutput4.png
  src/main/java/unicash/logic/commands/AddTransactionCommand.java
  src/main/java/unicash/model/Model.java
  src/main/java/unicash/model/ModelManager.java
  src/main/java/unicash/model/UniCash.java
  src/main/java/unicash/model/commons/Amount.java
  src/main/java/unicash/model/transaction/TransactionList.java
  src/main/java/unicash/model/transaction/exceptions/MaxTransactionException.java
  src/test/java/unicash/logic/commands/AddTransactionCommandTest.java
  src/test/java/unicash/logic/commands/SetBudgetCommandTest.java
  src/test/java/unicash/model/ModelManagerTest.java
  src/test/java/unicash/model/UniCashTest.java
  src/test/java/unicash/model/transaction/TransactionListTest.java
  src/test/java/unicash/testutil/TypicalTransactions.java
Labels: priority.High

#147 Migrate to new layout
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#174 Fix user reported bugs
  docs/UserGuide.md
Labels: documentation

#175 Addressing mock PE comments + adding constraints documentation
  docs/UserGuide.md
  docs/_layouts/page.html
  docs/_sass/minima/initialize.scss
  docs/assets/css/style.scss
Labels: documentation

#176 Add cases to list command & fix minor typo
  docs/UserGuide.md
  docs/images/unicash/command-outputs/list/noTransactions.png
  docs/images/unicash/command-outputs/list/withTransactions.png
Labels: documentation

#178 DG docs for storage component
  docs/DeveloperGuide.md
  docs/assets/css/style.scss
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: documentation

#179 Fix use case numbering
  docs/DeveloperGuide.md
Labels: documentation

#182 Improve phrasing of CI docs
  docs/DeveloperGuide.md
Labels: documentation

#177 Updating PPP
  docs/AboutUs.md
  docs/team/woojiahao.md
Labels: documentation

#185 Clean up UG documentation for GetTotalExpenditure and the budget managment commands
  docs/UserGuide.md
Labels: documentation

#184 Add documentation for budget management
  docs/DeveloperGuide.md
  docs/diagrams/unicash/budget-management/ClearBudgetSequenceDiagram.puml
  docs/diagrams/unicash/budget-management/GetBudgetSequenceDiagram.puml
  docs/diagrams/unicash/budget-management/SetBudgetActivityDiagram.puml
  docs/diagrams/unicash/budget-management/SetBudgetSequenceDiagram.puml
  docs/images/unicash/budget-management/ClearBudgetSequenceDiagram.png
  docs/images/unicash/budget-management/GetBudgetSequenceDiagram.png
  docs/images/unicash/budget-management/SetBudgetActivityDiagram.png
  docs/images/unicash/budget-management/SetBudgetSequenceDiagram.png
Labels: documentation

#180 Adding documentation for message builder
  docs/DeveloperGuide.md
  docs/assets/css/style.scss
  docs/diagrams/unicash/message-builder/MessageUsageGenerationClassDiagram.puml
  docs/images/unicash/message-builder/MessageUsageGenerationClassDiagram.png
Labels: documentation

#181 Add use cases for budget management
  docs/DeveloperGuide.md
Labels: documentation

#186 Update PPP - lipwei1808
  docs/team/lipwei1808.md
Labels: documentation

#187 Update UG for add transaction
  docs/UserGuide.md
Labels: documentation

#183 Update PPP
  docs/AboutUs.md
  docs/team/jamz903.md
Labels: documentation

#189 Fix explanation of DateTime default value
  docs/UserGuide.md
Labels: documentation

#191 Add and Enhance Unit Tests
  src/test/java/unicash/logic/parser/SetBudgetCommandParserTest.java
  src/test/java/unicash/model/budget/BudgetTest.java
  src/test/java/unicash/model/transaction/TransactionTest.java
Labels: type.Enhancement

#195 Update PPP
  docs/AboutUs.md
  docs/team/sp4ce-cowboy.md
Labels: documentation

#193 Update PPP - Ernest
  docs/AboutUs.md
  docs/team/elhy1999.md
Labels: documentation

#204 [Bug Fix] Fixed the duplicate transactions bug
  src/main/java/unicash/model/ReadOnlyUniCash.java
  src/main/java/unicash/model/transaction/Transaction.java
  src/main/java/unicash/model/transaction/TransactionList.java
Labels: type.Bug

#202 [Bug Fix] FindCommand bug fixed
  src/main/java/unicash/commons/enums/CommandType.java
  src/main/java/unicash/logic/commands/FindCommand.java
  src/main/java/unicash/logic/parser/FindCommandParser.java
  src/main/java/unicash/model/transaction/predicates/TransactionCategoryContainsKeywordsPredicate.java
  src/main/java/unicash/model/transaction/predicates/TransactionContainsAllKeywordsPredicate.java
  src/main/java/unicash/model/transaction/predicates/TransactionLocationContainsKeywordsPredicate.java
  src/main/java/unicash/model/transaction/predicates/TransactionNameContainsKeywordsPredicate.java
  src/main/java/unicash/ui/HelpWindow.java
  src/test/java/unicash/logic/parser/FindCommandParserTest.java
Labels: documentation, type.Bug

#199 Add Logic and Model component to DG
  docs/DeveloperGuide.md
  docs/diagrams/unicash/LogicClassDiagram.puml
  docs/diagrams/unicash/ModelClassDiagram.puml
  docs/diagrams/unicash/ParserClasses.puml
  docs/images/unicash/LogicClassDiagram.png
  docs/images/unicash/ModelClassDiagram.png
  docs/images/unicash/ParserClasses.png
Labels: documentation

#205 [UI Tests] Rolling Balance + Comprehensive UI Testing
  src/test/java/unicash/testutil/TestDataUtil.java
  src/test/java/unicash/testutil/UserInputBuilder.java
  src/test/java/unicash/ui/MainAppUiTest.java
  src/test/java/unicash/ui/RollingBalanceUiTest.java
Labels: type.Testing

#212 Refine UG Installation, Add, Help
  docs/UserGuide.md
Labels: documentation

#211 Latest round of UG/DG/PPP updates
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/unicash/budget-management/ClearBudgetSequenceDiagram.puml
  docs/diagrams/unicash/budget-management/SetBudgetSequenceDiagram.puml
  docs/images/unicash/budget-management/ClearBudgetSequenceDiagram.png
  docs/images/unicash/budget-management/SetBudgetSequenceDiagram.png
  docs/team/woojiahao.md
Labels: documentation

#208 [Documentation] Update UG with UI, Delete, Get, Find, Clear, Reset Commands
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/unicash/HelpPopUpNew.png
  docs/images/unicash/command-outputs/clearTransactions/clear.png
  docs/images/unicash/command-outputs/deleteTransaction/deleteTransactionInitialState2.png
  docs/images/unicash/command-outputs/deleteTransaction/deleteTransactionSuccess2FinalState.png
  docs/images/unicash/command-outputs/find/Find2.png
  docs/images/unicash/command-outputs/find/Find3.png
  docs/images/unicash/command-outputs/find/FindFriends.png
  docs/images/unicash/command-outputs/getTransaction/GetInitial3.png
  docs/images/unicash/command-outputs/getTransaction/GetSuccess.png
Labels: documentation

#194 Update DG with Summary Feature and Use Cases
  docs/DeveloperGuide.md
  docs/diagrams/unicash/EditTransactionSequenceDiagram.puml
  docs/diagrams/unicash/SummaryActivityDiagram.puml
  docs/diagrams/unicash/SummaryExecuteSequenceDiagram.puml
  docs/diagrams/unicash/SummaryUiSequenceDiagram.puml
  docs/images/unicash/EditTransactionSequenceDiagram.png
  docs/images/unicash/SummaryActivityDiagram.png
  docs/images/unicash/SummaryExecuteSequenceDiagram.png
  docs/images/unicash/SummaryUiSequenceDiagram.png
Labels: documentation

#215 Simplify sequence diagrams and fix installation instructions
  docs/DeveloperGuide.md
  docs/diagrams/unicash/budget-management/ClearBudgetSequenceDiagram.puml
  docs/diagrams/unicash/budget-management/GetBudgetSequenceDiagram.puml
  docs/diagrams/unicash/budget-management/SetBudgetSequenceDiagram.puml
  docs/diagrams/unicash/get-total-expenditure/GetTotalExpenditureSequenceDiagram.puml
  docs/images/unicash/budget-management/ClearBudgetSequenceDiagram.png
  docs/images/unicash/budget-management/GetBudgetSequenceDiagram.png
  docs/images/unicash/budget-management/SetBudgetSequenceDiagram.png
  docs/images/unicash/get-total-expenditure/GetTotalExpenditureSequenceDiagram.png
Labels: documentation

#219 Minor Touch-up to DG and SummaryWindow
  docs/DeveloperGuide.md
  docs/diagrams/unicash/EditTransactionSequenceDiagram.puml
  docs/images/unicash/EditTransactionSequenceDiagram.png
  docs/team/elhy1999.md
  src/main/java/unicash/ui/SummaryWindow.java
Labels: type.Enhancement, type.Bug

#221 Add user stories and manual testing steps to DG
  docs/DeveloperGuide.md
  docs/images/unicash/UiClassDiagram.png
Labels: documentation

#220 Fix find example bug
  src/main/java/unicash/commons/enums/CommandType.java
Labels: type.Bug

#223 [Documentation] DG Final Updates
  docs/DeveloperGuide.md
Labels: documentation
