Repository AY2324S1-CS2103-T16-3/tp, pull requests merged in 2023-10, with the labels that each got.

#27 Add Expense model
  src/main/java/seedu/address/model/expense/Amount.java
  src/main/java/seedu/address/model/expense/Category.java
  src/main/java/seedu/address/model/expense/Expense.java
  src/main/java/seedu/address/model/expense/Location.java
  src/main/java/seedu/address/model/expense/Name.java
  src/test/java/seedu/address/model/expense/AmountTest.java
  src/test/java/seedu/address/model/expense/CategoryTest.java
  src/test/java/seedu/address/model/expense/ExpenseTest.java
  src/test/java/seedu/address/model/expense/LocationTest.java
  src/test/java/seedu/address/model/expense/NameTest.java
  src/test/java/seedu/address/testutil/ExpenseBuilder.java
  src/test/java/seedu/address/testutil/TypicalExpenses.java
Labels: type.Enhancement, priority.High

#38 Update README with new UI mockup
  docs/images/Ui.png
Labels: documentation

#41 Update AboutUs.md
  docs/AboutUs.md
  docs/images/elhy1999.png
  docs/team/elhy1999.md
Labels: documentation

#42 Update User Guide with 'Edit Expense' feature
  docs/UserGuide.md
Labels: documentation

#52 Add Use Cases for income features to DG
  docs/DeveloperGuide.md
Labels: documentation

#56 Add Use Cases for List, Find, and Tabulate Total Expenses to DG
  docs/DeveloperGuide.md
Labels: documentation

#62 Add DeleteTransaction functionality
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/UniCashMessages.java
  src/main/java/seedu/address/logic/commands/transaction/AddTransactionCommand.java
  src/main/java/seedu/address/logic/commands/transaction/DeleteTransactionCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/transaction/AddTransactionCommandParser.java
  src/main/java/seedu/address/logic/parser/transaction/DeleteTransactionCommandParser.java
  src/main/java/seedu/address/model/transaction/TransactionNameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/UniCashMessagesTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/transaction/AddTransactionCommandTest.java
  src/test/java/seedu/address/logic/commands/transaction/DeleteTransactionCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/transaction/DeleteTransactionCommandParserTest.java
  src/test/java/seedu/address/model/transaction/TransactionNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High

#63 Add clear transactions command functionality
  src/main/java/seedu/address/logic/commands/transaction/ClearTransactionsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/transaction/DeleteTransactionCommandParser.java
  src/test/java/seedu/address/logic/commands/transaction/ClearTransactionsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.Medium

#66 Update handling of invalid values for non-compulsary fields
  src/main/java/seedu/address/logic/commands/transaction/GetTotalExpenditureCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/transaction/DateTime.java
  src/test/java/seedu/address/logic/commands/transaction/GetTotalExpenditureCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/transaction/CategoryTest.java
  src/test/java/seedu/address/model/transaction/DateTimeTest.java
  src/test/java/seedu/address/model/transaction/LocationTest.java
Labels: type.Bug, priority.High

#68 Support persisting of transactions into file
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/transaction/Category.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTransaction.java
  src/main/java/seedu/address/storage/JsonSerializableUniCash.java
  src/main/java/seedu/address/storage/JsonUniCashStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/UniCashStorage.java
  src/test/data/JsonSerializableUniCashTest/duplicateTransactionUniCash.json
  src/test/data/JsonSerializableUniCashTest/invalidTransactionUniCash.json
  src/test/data/JsonSerializableUniCashTest/typicalTransactionUniCash.json
  src/test/data/JsonUniCashStorageTest/invalidAndValidTransactionUniCash.json
  src/test/data/JsonUniCashStorageTest/invalidTransactionUniCash.json
  src/test/data/JsonUniCashStorageTest/notJsonFormatUniCash.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/transaction/AddTransactionCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/transaction/CategoryTest.java
  src/test/java/seedu/address/model/transaction/LocationTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTransactionTest.java
  src/test/java/seedu/address/storage/JsonSerializableUniCashTest.java
  src/test/java/seedu/address/storage/JsonUniCashStorageTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Enhancement, priority.High, severity.High

#64 Add Edit Transaction functionality
  src/main/java/seedu/address/logic/commands/transaction/EditTransactionCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/transaction/EditTransactionCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/transaction/AddTransactionCommandTest.java
  src/test/java/seedu/address/logic/commands/transaction/EditTransactionCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/transaction/EditTransactionCommandParserTest.java
  src/test/java/seedu/address/testutil/EditTransactionDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TransactionBuilder.java
  src/test/java/seedu/address/testutil/TransactionUtil.java
Labels: priority.High

#78 Update GUI
  src/main/java/unicash/MainApp.java
  src/main/java/unicash/model/category/Category.java
  src/main/java/unicash/ui/HelpWindow.java
  src/main/java/unicash/ui/MainWindow.java
  src/main/java/unicash/ui/StatusBarFooter.java
  src/main/java/unicash/ui/TransactionListPanel.java
  src/main/java/unicash/ui/UiManager.java
  src/main/resources/fonts/Inter-Bold.ttf
  src/main/resources/fonts/Inter-Medium.ttf
  src/main/resources/fonts/Inter-Regular.ttf
  src/main/resources/fonts/Inter-SemiBold.ttf
  src/main/resources/images/address_book_32.png
  src/main/resources/images/wallet_icon.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/main/resources/view/TransactionListPanel.fxml
  src/test/java/unicash/commons/util/AppUtilTest.java
  src/test/java/unicash/logic/commands/GetTotalExpenditureCommandTest.java
Labels: type.Enhancement, severity.Low

#80 Fix GetTotalExpenditure for expense w/ no category
  src/main/java/unicash/logic/commands/GetTotalExpenditureCommand.java
  src/test/java/unicash/logic/commands/GetTotalExpenditureCommandTest.java
Labels: type.Bug, priority.High, severity.High

#82 Add SplitPane GUI, local UserGuide and some other minor changes
  src/main/java/unicash/logic/LogicManager.java
  src/main/java/unicash/logic/UniCashMessages.java
  src/main/java/unicash/logic/commands/AddTransactionCommand.java
  src/main/java/unicash/logic/commands/DeleteTransactionCommand.java
  src/main/java/unicash/logic/commands/EditTransactionCommand.java
  src/main/java/unicash/logic/commands/FindCommand.java
  src/main/java/unicash/logic/commands/GetTotalExpenditureCommand.java
  src/main/java/unicash/logic/commands/HelpCommandUniCash.java
  src/main/java/unicash/logic/commands/ListCommand.java
  src/main/java/unicash/logic/parser/UniCashParser.java
  src/main/java/unicash/model/transaction/Amount.java
  src/main/java/unicash/model/util/SampleDataUtil.java
  src/main/java/unicash/ui/HelpWindow.java
  src/main/java/unicash/ui/MainWindow.java
  src/main/java/unicash/ui/StatusBarFooter.java
  src/main/java/unicash/ui/TransactionCard.java
  src/main/resources/documents/userguide_local.pdf
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/TransactionCard.fxml
  src/test/data/JsonSerializableUniCashTest/typicalTransactionUniCash.json
  src/test/java/unicash/logic/parser/UniCashParserTest.java
  src/test/java/unicash/model/transaction/AmountTest.java
Labels: priority.Medium

#92 Budget Model
  src/main/java/unicash/commons/enums/BudgetInterval.java
  src/main/java/unicash/commons/enums/TransactionType.java
  src/main/java/unicash/logic/commands/EditTransactionCommand.java
  src/main/java/unicash/logic/parser/AddTransactionCommandParser.java
  src/main/java/unicash/logic/parser/ParserUtil.java
  src/main/java/unicash/model/budget/Budget.java
  src/main/java/unicash/model/budget/Interval.java
  src/main/java/unicash/model/commons/Amount.java
  src/main/java/unicash/model/transaction/Transaction.java
  src/main/java/unicash/model/util/SampleDataUtil.java
  src/main/java/unicash/storage/JsonAdaptedTransaction.java
  src/main/java/unicash/ui/TransactionCard.java
  src/test/java/unicash/logic/parser/AddTransactionCommandParserTest.java
  src/test/java/unicash/logic/parser/EditTransactionCommandParserTest.java
  src/test/java/unicash/logic/parser/ParserUtilTest.java
  src/test/java/unicash/model/budget/BudgetTest.java
  src/test/java/unicash/model/budget/IntervalTest.java
  src/test/java/unicash/model/commons/AmountTest.java
  src/test/java/unicash/storage/JsonAdaptedTransactionTest.java
  src/test/java/unicash/testutil/BudgetBuilder.java
  src/test/java/unicash/testutil/EditTransactionDescriptorBuilder.java
  src/test/java/unicash/testutil/TransactionBuilder.java
  src/test/java/unicash/testutil/TypicalBudgets.java
Labels: type.Story, type.Task, priority.High

#87 Add support for user to input multiple dateTime formats
  src/main/java/unicash/model/transaction/DateTime.java
  src/main/java/unicash/storage/JsonAdaptedTransaction.java
  src/test/java/unicash/model/transaction/DateTimeTest.java
  src/test/java/unicash/storage/JsonAdaptedTransactionTest.java
  src/test/java/unicash/testutil/TransactionUtil.java
Labels: type.Story, severity.Low

#95 DG - AddTransactionCommand
  docs/DeveloperGuide.md
  docs/diagrams/unicash/AddTransactionActivityDiagram.puml
  docs/diagrams/unicash/AddTransactionSequenceDiagram.puml
  docs/diagrams/unicash/BudgetClassDiagram.puml
  docs/diagrams/unicash/TransactionClassDiagram.puml
  docs/images/unicash/AddTransactionActivityDiagram.png
  docs/images/unicash/AddTransactionSequenceDiagram.png
  docs/images/unicash/TransactionClassDiagram.png
Labels: documentation

#97 Add constraint to model
  src/main/java/unicash/model/transaction/Location.java
  src/main/java/unicash/model/transaction/Name.java
  src/test/java/unicash/logic/commands/CommandTestUtil.java
  src/test/java/unicash/storage/JsonAdaptedTransactionTest.java
Labels: type.Enhancement, priority.Low

#96 UI Modifications and some bug fixes
  build.gradle
  src/main/java/unicash/logic/UniCashMessages.java
  src/main/java/unicash/logic/commands/AddTransactionCommand.java
  src/main/java/unicash/logic/commands/DeleteTransactionCommand.java
  src/main/java/unicash/logic/commands/EditTransactionCommand.java
  src/main/java/unicash/logic/commands/HelpCommand.java
  src/main/java/unicash/logic/parser/ParserUtil.java
  src/main/java/unicash/model/category/Category.java
  src/main/java/unicash/model/category/UniqueCategoryList.java
  src/main/java/unicash/model/commons/Amount.java
  src/main/java/unicash/model/transaction/Transaction.java
  src/main/java/unicash/model/transaction/Type.java
  src/main/java/unicash/ui/MainWindow.java
  src/main/java/unicash/ui/StatusBarFooter.java
  src/main/java/unicash/ui/StyleSheet.java
  src/main/java/unicash/ui/TransactionCard.java
  src/main/java/unicash/ui/TransactionListPanel.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/main/resources/view/TransactionCard.fxml
  src/test/java/unicash/logic/commands/EditTransactionCommandTest.java
  src/test/java/unicash/logic/commands/GetTotalExpenditureCommandTest.java
  src/test/java/unicash/logic/commands/HelpCommandTest.java
  src/test/java/unicash/model/category/UniqueCategoryListTest.java
  src/test/java/unicash/model/commons/AmountTest.java
  src/test/java/unicash/model/transaction/TransactionTest.java
  src/test/java/unicash/testutil/TransactionUtil.java
  src/test/java/unicash/ui/StyleSheetTest.java
Labels: priority.Medium

#93 Setup TestFX
  .github/workflows/gradle.yml
  .github/workflows/unit_test.yml
  build.gradle
  src/main/java/unicash/MainApp.java
  src/test/java/unicash/ui/HelpWindowUiTest.java
  src/test/java/unicash/ui/MainAppIntegrationUiTest.java
  src/test/java/unicash/ui/MainAppUiTest.java
Labels: type.Enhancement, priority.Medium, severity.Low

#101 Add Enhanced Find Command and Get Command
  src/main/java/unicash/commons/util/StringUtil.java
  src/main/java/unicash/logic/UniCashMessages.java
  src/main/java/unicash/logic/commands/FindCommand.java
  src/main/java/unicash/logic/commands/GetCommand.java
  src/main/java/unicash/logic/commands/ListCommand.java
  src/main/java/unicash/logic/parser/FindCommandParser.java
  src/main/java/unicash/logic/parser/GetCommandParser.java
  src/main/java/unicash/logic/parser/UniCashParser.java
  src/main/java/unicash/model/category/UniqueCategoryList.java
  src/main/java/unicash/model/commons/Amount.java
  src/main/java/unicash/model/transaction/DateTime.java
  src/main/java/unicash/model/transaction/predicates/TransactionAmountContainsValuePredicate.java
  src/main/java/unicash/model/transaction/predicates/TransactionCategoryContainsKeywordsPredicate.java
  src/main/java/unicash/model/transaction/predicates/TransactionContainsKeywordsPredicate.java
  src/main/java/unicash/model/transaction/predicates/TransactionDateTimeContainsValuePredicate.java
  src/main/java/unicash/model/transaction/predicates/TransactionLocationContainsKeywordsPredicate.java
  src/main/java/unicash/model/transaction/predicates/TransactionNameContainsKeywordsPredicate.java
  src/main/java/unicash/model/transaction/predicates/TransactionTypeContainsValuePredicate.java
  src/test/java/unicash/commons/util/StringUtilTest.java
  src/test/java/unicash/logic/commands/CommandTestUtil.java
  src/test/java/unicash/logic/commands/FindCommandTest.java
  src/test/java/unicash/logic/commands/GetCommandTest.java
  src/test/java/unicash/logic/commands/HelpCommandTest.java
  src/test/java/unicash/logic/parser/FindCommandParserTest.java
  src/test/java/unicash/logic/parser/UniCashParserTest.java
  src/test/java/unicash/model/ModelManagerTest.java
  src/test/java/unicash/model/category/UniqueCategoryListTest.java
  src/test/java/unicash/model/transaction/predicates/TransactionAmountContainsValuePredicateTest.java
  src/test/java/unicash/model/transaction/predicates/TransactionCategoryContainsKeywordsPredicateTest.java
  src/test/java/unicash/model/transaction/predicates/TransactionContainsKeywordsPredicateTest.java
  src/test/java/unicash/model/transaction/predicates/TransactionDateTimeContainsValuePredicateTest.java
  src/test/java/unicash/model/transaction/predicates/TransactionLocationContainsKeywordsPredicateTest.java
  src/test/java/unicash/model/transaction/predicates/TransactionNameContainsKeywordsPredicateTest.java
  src/test/java/unicash/model/transaction/predicates/TransactionTypeContainsValuePredicateTest.java
Labels: priority.High

#104 Update Developer Guide with Delete and Clear Commands
  docs/DeveloperGuide.md
  docs/diagrams/unicash/ClearTransactionsActivityDiagram.puml
  docs/diagrams/unicash/ClearTransactionsSequenceDiagram.puml
  docs/diagrams/unicash/DeleteTransactionActivityDiagram.puml
  docs/diagrams/unicash/DeleteTransactionSequenceDiagram.puml
  docs/images/unicash/ClearTransactionsActivityDiagram.png
  docs/images/unicash/ClearTransactionsSequenceDiagram.png
  docs/images/unicash/DeleteTransactionActivityDiagram.png
  docs/images/unicash/DeleteTransactionSequenceDiagram.png
  docs/team/sp4ce-cowboy.md
Labels: documentation

#106 Update DG with Edit Transaction command
  docs/DeveloperGuide.md
  docs/diagrams/unicash/EditTransactionSequenceDiagram.puml
  docs/images/unicash/EditTransactionSequenceDiagram.png
Labels: documentation

#100 Add Summary Statistics Feature
  src/main/java/unicash/logic/Logic.java
  src/main/java/unicash/logic/LogicManager.java
  src/main/java/unicash/logic/UniCashMessages.java
  src/main/java/unicash/logic/commands/CommandResult.java
  src/main/java/unicash/logic/commands/SummaryCommand.java
  src/main/java/unicash/logic/parser/UniCashParser.java
  src/main/java/unicash/model/Model.java
  src/main/java/unicash/model/ModelManager.java
  src/main/java/unicash/model/UniCash.java
  src/main/java/unicash/model/transaction/Transaction.java
  src/main/java/unicash/ui/MainWindow.java
  src/main/java/unicash/ui/SummaryWindow.java
  src/main/resources/view/SummaryWindow.fxml
  src/test/java/unicash/logic/LogicManagerTest.java
  src/test/java/unicash/logic/commands/AddTransactionCommandTest.java
  src/test/java/unicash/logic/commands/CommandResultTest.java
  src/test/java/unicash/logic/commands/SummaryCommandTest.java
  src/test/java/unicash/logic/parser/UniCashParserTest.java
  src/test/java/unicash/model/ModelManagerTest.java
  src/test/java/unicash/model/UniCashTest.java
  src/test/java/unicash/model/transaction/TransactionTest.java
  src/test/java/unicash/testutil/TypicalTransactions.java
  src/test/java/unicash/ui/MainAppIntegrationUiTest.java
  src/test/java/unicash/ui/SummaryWindowUiTest.java
Labels: type.Story, priority.High

#115 Add year support for get total expenditure
  src/main/java/unicash/commons/util/StringUtil.java
  src/main/java/unicash/logic/UniCashMessages.java
  src/main/java/unicash/logic/commands/GetTotalExpenditureCommand.java
  src/main/java/unicash/logic/parser/GetTotalExpenditureCommandParser.java
  src/test/java/unicash/commons/util/StringUtilTest.java
  src/test/java/unicash/logic/commands/GetTotalExpenditureCommandTest.java
  src/test/java/unicash/logic/parser/GetTotalExpenditureCommandParserTest.java
Labels: type.Enhancement, priority.Medium, severity.Low

#110 [Minor UI Update] Add Command History
  src/main/java/unicash/MainApp.java
  src/main/java/unicash/commons/core/LogsCenter.java
  src/main/java/unicash/ui/CommandBox.java
  src/test/java/unicash/logic/commands/AddTransactionCommandTest.java
  src/test/java/unicash/logic/commands/CommandTestUtil.java
  src/test/java/unicash/storage/StorageManagerTest.java
  src/test/java/unicash/ui/CommandBoxUiTest.java
Labels: priority.Medium

#116 Fix datetime inputString bug
  src/main/java/unicash/model/category/UniqueCategoryList.java
  src/main/java/unicash/model/transaction/DateTime.java
  src/main/java/unicash/storage/JsonSerializableUniCash.java
  src/test/java/unicash/model/category/UniqueCategoryListTest.java
  src/test/java/unicash/model/transaction/DateTimeTest.java
  src/test/java/unicash/storage/JsonAdaptedTransactionIntegrationTest.java
  src/test/java/unicash/storage/JsonAdaptedTransactionTest.java
  src/test/java/unicash/storage/JsonSerializableUniCashTest.java
Labels: type.Bug, priority.High, severity.High

#121 Developer Guide - Transaction
  docs/DeveloperGuide.md
  docs/diagrams/unicash/AddTransactionSequenceDiagram.puml
  docs/images/unicash/AddTransactionSequenceDiagram.png
  docs/images/unicash/BudgetClassDiagram.png
Labels: documentation

#123 User Guide Skeleton
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/unicash/command-outputs/addTransactionFailedOutput1.png
  docs/images/unicash/command-outputs/addTransactionFailedOutput2.png
  docs/images/unicash/command-outputs/addTransactionFailedOutput3.png
  docs/images/unicash/command-outputs/addTransactionSuccessOutput1.png
  docs/images/unicash/command-outputs/addTransactionSuccessOutput2.png
Labels: documentation

#119 [Patch] Update CommandBox History
  src/main/java/unicash/ui/CommandBox.java
  src/test/java/unicash/ui/CommandBoxUiTest.java
Labels: priority.Medium

#117 Implement command usage message builder
  src/main/java/unicash/commons/util/CommandUsage.java
  src/main/java/unicash/commons/util/ExampleGenerator.java
  src/main/java/unicash/logic/commands/AddTransactionCommand.java
  src/main/java/unicash/logic/commands/DeleteTransactionCommand.java
  src/main/java/unicash/logic/commands/EditTransactionCommand.java
  src/main/java/unicash/logic/commands/FindCommand.java
  src/main/java/unicash/logic/commands/GetCommand.java
  src/main/java/unicash/logic/commands/GetTotalExpenditureCommand.java
  src/main/java/unicash/logic/commands/HelpCommand.java
  src/main/java/unicash/logic/commands/ListCommand.java
  src/main/java/unicash/logic/commands/SummaryCommand.java
  src/test/java/unicash/commons/util/CommandUsageBuilderTest.java
  src/test/java/unicash/commons/util/CommandUsageTest.java
  src/test/java/unicash/commons/util/ExampleGeneratorTest.java
Labels: type.Enhancement, priority.Low, severity.Low

#126 [For Test-branch] Add Test Command
  src/main/java/unicash/logic/commands/TestCommand.java
  src/main/java/unicash/logic/parser/UniCashParser.java
  src/main/java/unicash/model/util/SampleDataUtil.java
Labels: priority.Low

#128 Help Command for specified commands
  src/main/java/unicash/logic/UniCashMessages.java
  src/main/java/unicash/logic/commands/ClearTransactionsCommand.java
  src/main/java/unicash/logic/commands/ExitCommand.java
  src/main/java/unicash/logic/commands/HelpCommand.java
  src/main/java/unicash/logic/commands/ResetCommand.java
  src/main/java/unicash/logic/parser/HelpCommandParser.java
  src/main/java/unicash/logic/parser/ListCommandParser.java
  src/main/java/unicash/logic/parser/UniCashParser.java
  src/test/java/unicash/logic/commands/HelpCommandTest.java
  src/test/java/unicash/logic/parser/HelpCommandParserTest.java
Labels: type.Enhancement, priority.Low

#134 [Documentation] Update UG with Delete and Get
  docs/UserGuide.md
  docs/images/unicash/command-outputs/deleteTransaction/InitialApplicationState.png
  docs/images/unicash/command-outputs/deleteTransaction/deleteFail1.png
  docs/images/unicash/command-outputs/deleteTransaction/deleteFail1Initial.png
  docs/images/unicash/command-outputs/deleteTransaction/deleteFail2.png
  docs/images/unicash/command-outputs/deleteTransaction/deleteTransactionInitialState.png
  docs/images/unicash/command-outputs/deleteTransaction/deleteTransactionInitialState2.png
  docs/images/unicash/command-outputs/deleteTransaction/deleteTransactionSuccess1FinalState.png
  docs/images/unicash/command-outputs/deleteTransaction/deleteTransactionSuccess2FinalState.png
  docs/images/unicash/command-outputs/getTransaction/getFail1.png
  docs/images/unicash/command-outputs/getTransaction/getFail2.png
  docs/images/unicash/command-outputs/getTransaction/getInitial1.png
  docs/images/unicash/command-outputs/getTransaction/getInitial2.png
  docs/images/unicash/command-outputs/getTransaction/getSuccessFinal1.png
  docs/images/unicash/command-outputs/getTransaction/getSuccessFinal2.png
  docs/img.png
Labels: documentation
